omron:
  omron_test_node:
    ros__parameters:
      use_close_loop: true
      cmd_vel_topic: "/omron/cmd_vel"
      pose_topic: "/omron/status/pose"
      max_vel_in_m: 0.5 # m/s
      max_acc_in_m: 1.0 # m/s^2
      max_rot_vel_in_deg: 30.0 # deg/s
      max_rot_acc_in_deg: 300.0 # deg/s^2
      motion_law:
        max_vel_in_m: [0.1, 0.2]
        max_acc_in_m: [0.2, 0.4]
        max_rot_vel_in_deg: [10.0]
        max_rot_acc_in_deg: [100.0]
      update_period_in_ms: 50 # ms

      movements: [0]
      values:    [2.0]

  omron_test_bag_node:
    ros__parameters:
      cmd_vel_topic: "/omron/cmd_vel"
      state_pose_topic: "/omron/status/pose"
      state_vel_topic: "/omron/status/velocity"
